product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /

users_bundle:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /auth

layout_bundle:
    resource: "@LayoutBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"




