users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /auth

layout:
    resource: "@LayoutBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


