product_product:
    resource: "@ProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

product_pdf:
    path:     /pdf/product
    defaults: { _controller: ProductBundle:GeneratorPDF:index }
